services:
  # Git sync service - monitors GitHub and rebuilds Hugo site
  gitsync:
    build:
      context: ..
      dockerfile: docker/gitsync.Dockerfile
    environment:
      - REPO_URL=https://github.com/styliteag/blog.git
      - SYNC_INTERVAL=60  # Check every 60 seconds
    volumes:
      - shared_data:/shared
    restart: unless-stopped
    
  # Nginx service - serves the built site
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "82:80"
    volumes:
      - shared_data:/shared
    depends_on:
      - gitsync
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`blog.stylite-live.de`)"
      - "traefik.http.routers.homepage.entrypoints=websecure"
      - "traefik.http.routers.homepage.tls.certresolver=letsencrypt"

volumes:
  shared_data: